language: node_js
node_js:
  - 13

services:
  - docker

install: 
  - echo "about to install"

before_install: 
  - echo "none"

script: 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed kaybolo/udagram-api-feed:v1
  - docker tag udagram-api-user kaybolo/udagram-api-user:v1
  - docker tag udagram-frontend kaybolo/udagram-frontend:v1
  - docker tag udagram-reverseproxy kaybolo/udagram-reverseproxy:v1

after_success: 
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kaybolo/udagram-api-feed:v1
  - docker push kaybolo/udagram-api-user:v1
  - docker push kaybolo/udagram-frontend:v1
  - docker push kaybolo/udagram-reverseproxy:v1